pipeline {
   /*  agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    } */
	agent {
        label 'WindowsNode'
    }
    stages {
        stage('Build') {
            steps {
		    bat(/"C:\Program Files\apache-maven-3.8.1\bin\mvn" -Dmaven.test.failure.ignore clean package/) 
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
